"""agent.py -- A9: attach a model to the mesh.

    subscribe -> verify LOCALLY -> authorize -> model turn -> signed reply

The daemon that makes ``examples/proposer|skeptic|arbiter.md`` executable. Until this
existed, Synnoesis moved messages BETWEEN agents but never ran one.

SECURITY POSTURE -- read this before extending the file
-------------------------------------------------------
**A verified message is AUTHENTIC, not SAFE.** A signature proves WHO sent it. It
never proves the content is benign, and it never proves the sender was ALLOWED to ask.
This daemon feeds signed message bodies to a language model, which is exactly where
that distinction stops being academic: a valid signature on a prompt injection is
still a valid signature.

Two structural answers, both deliberate:

1. **NO TOOLS.** The model turn is text-in -> text-out. No filesystem, no shell, no
   network egress beyond the configured model endpoint. We do NOT attempt to DETECT
   injection -- detection is a semantic classifier, and a semantic classifier cannot
   carry a security boundary. We remove what an injected agent could reach instead.
   An injected agent can be talked into SAYING anything and can DO nothing.

2. **AUTHORIZATION IS SEPARATE FROM VERIFICATION.** Keyring membership answers "who is
   this?". ``respond_to`` answers "will I act on it?". Conflating them would mean
   anyone whose key you have ever enrolled can drive your agent. ``respond_to``
   defaults to EMPTY -- this daemon replies to nobody until you say who.

🔴 **AND THE HALF THAT IS EASY TO MISS -- the OUTPUT side.**
"No tools, so it can do nothing" is only half true. This daemon SIGNS ITS REPLIES.
Untrusted content arrives, the model processes it, and the result leaves **under this
agent's key**. Content that entered unauthenticated leaves AUTHENTICATED. The daemon
itself is harmless; it is a **signature-laundering step**. If a downstream peer has
tools, an injection can chain THROUGH this agent to reach them.

    A SIGNED AGENT REPLY IS AUTHENTIC AND UNVETTED.

Consumers of this daemon's output must not treat "verify=ok" as "safe to act on".
That is stated here, in the docs, and in the reply banner rather than encoded as a
wire field -- adding one would change the frozen message contract, which this release
deliberately does not touch.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import sign      # noqa: E402  -- Ed25519 + keyring + DS_TAG_ENVELOPE
import paths     # noqa: E402  -- portable data-home resolver
import mqtt as mq  # noqa: E402  -- broker transport + security floor
import listen    # noqa: E402  -- REUSE process_incoming: one trust boundary, not two

# Config is JSON, not TOML: `tomllib` landed in 3.11 and this package supports 3.10+,
# so TOML would need a third-party parser. JSON is stdlib everywhere we run.
CONFIG_KEYS_REQUIRED = ("agent_id", "base_url", "model", "system_prompt")
CONFIG_KEYS_OPTIONAL = ("api_key_env", "respond_to", "max_replies_per_window",
                        "window_sec", "request_timeout_sec")

# Defaults are LOGGED at startup, never silent -- they are meant to be tuned from real
# trip data rather than trusted as tuned. A constant nobody has seen trip is a guess.
DEFAULT_MAX_REPLIES = 20
DEFAULT_WINDOW_SEC = 600
DEFAULT_TIMEOUT_SEC = 120

UNVETTED_BANNER = "[synnoesis: authentic, unvetted -- generated by an agent from an untrusted prompt]"


class ConfigError(Exception):
    """Raised for a config that cannot be trusted. Always fatal -- never defaulted past."""


@dataclass
class AgentConfig:
    agent_id: str
    base_url: str
    model: str
    system_prompt: str
    api_key_env: str = ""
    respond_to: tuple = ()
    max_replies_per_window: int = DEFAULT_MAX_REPLIES
    window_sec: int = DEFAULT_WINDOW_SEC
    request_timeout_sec: int = DEFAULT_TIMEOUT_SEC
    # True only when the key came from an env var that was actually set.
    api_key: str = ""


@dataclass
class Budget:
    """Per-process rolling reply budget -- the loop containment for this release.

    Two A9 agents pointed at each other reply forever. A signed hop-counter would bound
    the CHAIN rather than one process, but it would have to join SIGNED_FIELDS or an
    attacker simply resets it -- a wire-contract change this release does not make.
    So containment is local: each process exhausts its own budget and stops.

    It is not transmitted, so it cannot be forged. It is also not shared, so it bounds
    what THIS process emits, not what the mesh as a whole does. Stated plainly because
    the difference matters: this is a cost/runaway guard, not a distributed cutoff.
    """
    limit: int
    window_sec: int
    stamps: list = field(default_factory=list)
    tripped_notice_sent_at: float = 0.0

    def _prune(self, now: float) -> None:
        cutoff = now - self.window_sec
        self.stamps = [t for t in self.stamps if t > cutoff]

    def allows(self, now: float) -> bool:
        self._prune(now)
        return len(self.stamps) < self.limit

    def record(self, now: float) -> None:
        self.stamps.append(now)

    def should_announce_trip(self, now: float) -> bool:
        """Announce an exhausted budget ONCE per window, not per dropped message.

        A silent budget trip is indistinguishable from a dead agent, and that ambiguity
        is expensive to debug -- so it is announced. But the announcement is itself a
        send, so announcing per-message would recreate the very flood being contained.
        """
        if now - self.tripped_notice_sent_at < self.window_sec:
            return False
        self.tripped_notice_sent_at = now
        return True


def load_config(path) -> AgentConfig:
    """Parse + validate. Every failure is fatal and names the fix.

    Fail-closed on purpose: a half-understood agent config is an agent answering
    people you did not intend it to answer.
    """
    p = Path(path).expanduser()
    if not p.is_file():
        raise ConfigError(f"config not found: {p}")
    try:
        raw = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise ConfigError(f"config is not valid JSON ({p}): {e}") from e
    if not isinstance(raw, dict):
        raise ConfigError(f"config must be a JSON object, got {type(raw).__name__}")

    # JSON has no comment syntax, so an underscore-prefixed key is the documented
    # convention for one. This does NOT weaken the unknown-key rejection below: a
    # typo of a real key ("respnod_to") does not start with an underscore, so it is
    # still caught. Commenting has to be opt-in and visible, not accidental.
    unknown = ({k for k in raw if not k.startswith("_")}
               - set(CONFIG_KEYS_REQUIRED) - set(CONFIG_KEYS_OPTIONAL))
    if unknown:
        # Reject rather than ignore: a typo'd `respond_to` silently ignored is an agent
        # with NO allowlist, which is the failure this whole file is shaped to prevent.
        raise ConfigError(f"unknown config key(s): {sorted(unknown)}; "
                          f"expected {sorted(CONFIG_KEYS_REQUIRED + CONFIG_KEYS_OPTIONAL)}")
    missing = [k for k in CONFIG_KEYS_REQUIRED if not str(raw.get(k) or "").strip()]
    if missing:
        raise ConfigError(f"config is missing required key(s): {missing}")

    prompt_path = Path(str(raw["system_prompt"])).expanduser()
    if not prompt_path.is_absolute():
        prompt_path = (p.parent / prompt_path).resolve()
    if not prompt_path.is_file():
        raise ConfigError(f"system_prompt file not found: {prompt_path}")
    try:
        prompt_text = prompt_path.read_text(encoding="utf-8")
    except OSError as e:
        raise ConfigError(f"cannot read system_prompt {prompt_path}: {e}") from e

    respond_to = raw.get("respond_to") or []
    if not isinstance(respond_to, list) or any(not isinstance(x, str) for x in respond_to):
        raise ConfigError("respond_to must be a list of agent-id strings")

    api_key = ""
    key_env = str(raw.get("api_key_env") or "").strip()
    if key_env:
        # The config names the ENV VAR; it never contains the secret. Mirrors the
        # SYN_BROKER_PASSFILE posture -- no secrets in config, none in argv.
        api_key = (os.environ.get(key_env) or "").strip()
        if not api_key:
            raise ConfigError(
                f"api_key_env names {key_env!r} but that variable is unset or empty. "
                f"Export it, or drop api_key_env if your endpoint needs no key.")

    def _pos_int(key, default):
        v = raw.get(key, default)
        if not isinstance(v, int) or isinstance(v, bool) or v <= 0:
            raise ConfigError(f"{key} must be a positive integer, got {v!r}")
        return v

    return AgentConfig(
        agent_id=str(raw["agent_id"]).strip(),
        base_url=str(raw["base_url"]).strip().rstrip("/"),
        model=str(raw["model"]).strip(),
        system_prompt=prompt_text,
        api_key_env=key_env,
        respond_to=tuple(respond_to),
        max_replies_per_window=_pos_int("max_replies_per_window", DEFAULT_MAX_REPLIES),
        window_sec=_pos_int("window_sec", DEFAULT_WINDOW_SEC),
        request_timeout_sec=_pos_int("request_timeout_sec", DEFAULT_TIMEOUT_SEC),
        api_key=api_key,
    )


@dataclass
class Action:
    kind: str          # 'reply' | 'refuse' | 'ignore'
    reason: str
    sender: str = "?"
    body: str = ""     # inbound body when kind == 'reply'


def decide(outer: dict, cfg: AgentConfig, budget: Budget, now: float) -> Action:
    """PURE authorization decision for one already-verified inbound record.

    Split out from the loop so tests exercise the real decision rather than a replica
    -- the same reason listen.process_incoming is pure. Verification already happened
    upstream (listen.process_incoming); this answers only "do we act on it?".
    """
    inner = outer.get("payload") if isinstance(outer.get("payload"), dict) else outer
    sender = str(inner.get("_from") or "?")
    body = str(inner.get("body") or "").strip()

    if sender == cfg.agent_id:
        return Action("ignore", "own message", sender=sender)
    if not body:
        return Action("ignore", "empty body", sender=sender)

    # AUTHORIZATION -- deliberately not keyring membership. See module docstring.
    if sender not in cfg.respond_to:
        if not cfg.respond_to:
            reason = (f"verified message from {sender!r}, but respond_to is EMPTY so this "
                      f"agent replies to nobody. Add {sender!r} to respond_to in your "
                      f"config to enable replies.")
        else:
            reason = (f"verified message from {sender!r}; {sender!r} is not in respond_to "
                      f"{list(cfg.respond_to)}. Add them to enable replies.")
        # A loud, instructive refusal -- NOT a looser default. Fail-closed stays; the
        # confusing part (silence) is what gets fixed.
        return Action("refuse", reason, sender=sender)

    if not budget.allows(now):
        return Action("refuse",
                      f"reply budget exhausted ({cfg.max_replies_per_window} replies / "
                      f"{cfg.window_sec}s). Loop containment tripped — raise "
                      f"max_replies_per_window if this is legitimate traffic.",
                      sender=sender)

    return Action("reply", "authorized", sender=sender, body=body)


def call_model(cfg: AgentConfig, user_text: str) -> str:
    """One OpenAI-compatible chat completion. Raises RuntimeError on any failure.

    🔴 NO `tools` / `functions` KEY IS SENT, EVER. That omission is the security
    property in section 1 of the module docstring, not an oversight -- a model that is
    never offered a tool cannot call one, regardless of what the prompt says. Do not
    add tool wiring here without the agent-type gate that does not yet exist.

    stdlib urllib rather than `requests`: the bare install is dependency-free and this
    is one small POST per turn, not a streaming read.
    """
    payload = {
        "model": cfg.model,
        "messages": [
            {"role": "system", "content": cfg.system_prompt},
            {"role": "user", "content": user_text},
        ],
        "stream": False,
    }
    data = json.dumps(payload).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if cfg.api_key:
        headers["Authorization"] = f"Bearer {cfg.api_key}"
    req = urllib.request.Request(f"{cfg.base_url}/chat/completions",
                                 data=data, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=cfg.request_timeout_sec) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        # Never echo the response body verbatim: an endpoint can reflect the
        # Authorization header or key material in its error payload.
        raise RuntimeError(f"model endpoint returned HTTP {e.code}") from e
    except (urllib.error.URLError, TimeoutError, OSError) as e:
        raise RuntimeError(f"model endpoint unreachable: {e.__class__.__name__}") from e
    except json.JSONDecodeError as e:
        raise RuntimeError("model endpoint returned non-JSON") from e

    try:
        text = body["choices"][0]["message"]["content"]
    except (KeyError, IndexError, TypeError) as e:
        raise RuntimeError("model response missing choices[0].message.content") from e
    if not isinstance(text, str) or not text.strip():
        raise RuntimeError("model returned an empty completion")
    return text.strip()


def _send_reply(cfg: AgentConfig, to: str, text: str) -> None:
    """Publish a signed reply. Prefixed with the unvetted banner -- see the OUTPUT-side
    warning in the module docstring: this reply is authentic and NOT vetted."""
    body = f"{UNVETTED_BANNER}\n{text}"
    inner = sign.new_message(cfg.agent_id, to, body, "normal")
    broker = mq.resolve_broker()
    if broker is None:
        raise RuntimeError("no broker configured (SYN_BROKER unset)")
    mq.publish_one(broker, f"agent/{to}/inbox",
                   json.dumps(inner, ensure_ascii=False).encode("utf-8"),
                   client_id=f"synnoesis-agent-{cfg.agent_id}")


def _log(line: str) -> None:
    print(f"[{datetime.now(timezone.utc).strftime('%H:%M:%SZ')}] {line}", flush=True)


def run(cfg: AgentConfig, *, max_age_sec: int) -> int:
    broker = mq.resolve_broker()
    if broker is None:
        print("error: agent requires a broker — set SYN_BROKER=host[:port].",
              file=sys.stderr)
        return 2
    # Enforce-signing is FORCED ON here regardless of environment. An agent-runner that
    # acts on unsigned traffic is not defensible, so this is not a user-tunable knob.
    if not sign.CRYPTO_AVAILABLE:
        print("error: the agent runner requires signature verification, but "
              "'cryptography' is not installed. Install it: pip install "
              "\"synnoesis[mqtt]\"", file=sys.stderr)
        return 1

    budget = Budget(limit=cfg.max_replies_per_window, window_sec=cfg.window_sec)
    seen: dict = {}
    inbox_path = paths.service_dir("comms", create=True) / f"{cfg.agent_id}-inbox.jsonl"

    def on_message(_client, _userdata, message):
        now_dt = datetime.now(timezone.utc)
        now = time.monotonic()
        d = listen.process_incoming(message.payload, me=cfg.agent_id,
                                    keyring=sign.load_keyring(), enforce=True,
                                    max_age_sec=max_age_sec, seen=seen, now=now_dt)
        if d.action != "append":
            _log(f"· dropped from {d.sender}: {d.reason}")
            return
        # Persist first: the inbox is the audit trail, and it must record what ARRIVED
        # even when the agent declines to answer it.
        try:
            with inbox_path.open("a", encoding="utf-8") as f:
                f.write(json.dumps(d.outer, ensure_ascii=False) + "\n")
        except OSError as e:
            _log(f"error: could not append to {inbox_path}: {e}")

        act = decide(d.outer, cfg, budget, now)
        if act.kind == "ignore":
            _log(f"· ignored from {act.sender}: {act.reason}")
            return
        if act.kind == "refuse":
            _log(f"⊘ REFUSED from {act.sender}: {act.reason}")
            # A budget trip is announced back to the peer once per window so an
            # exhausted agent is distinguishable from a dead one. An unauthorized
            # sender gets NO reply -- answering them would leak that we are here and
            # would let an unlisted peer make us emit traffic.
            if "budget exhausted" in act.reason and budget.should_announce_trip(now):
                try:
                    _send_reply(cfg, act.sender,
                                "reply budget exhausted; not responding this window.")
                except RuntimeError as e:
                    _log(f"error: could not send budget notice: {e}")
            return

        try:
            answer = call_model(cfg, act.body)
        except RuntimeError as e:
            # LOUD, never silent: a provider failure that looks like a quiet agent is
            # the ambiguity we are explicitly designing against.
            _log(f"error: model turn failed for {act.sender}: {e}")
            try:
                _send_reply(cfg, act.sender, f"agent error: {e}")
            except RuntimeError as e2:
                _log(f"error: could not send failure notice: {e2}")
            return

        budget.record(now)
        try:
            _send_reply(cfg, act.sender, answer)
        except RuntimeError as e:
            _log(f"error: could not publish reply to {act.sender}: {e}")
            return
        _log(f"→ replied to {act.sender} ({len(answer)} chars, "
             f"{len(budget.stamps)}/{cfg.max_replies_per_window} in window)")

    def on_ready(host, top):
        _log(f"agent {cfg.agent_id!r} up on {host} [{top}]")
        _log(f"  model      : {cfg.model} @ {cfg.base_url}")
        _log(f"  tools      : NONE (text-in/text-out; replies are authentic + UNVETTED)")
        _log(f"  respond_to : {list(cfg.respond_to) or 'EMPTY — replies to nobody'}")
        # Defaults are logged so they are tuned from observed trips, not guessed.
        is_default = (cfg.max_replies_per_window == DEFAULT_MAX_REPLIES
                      and cfg.window_sec == DEFAULT_WINDOW_SEC)
        _log(f"  budget     : {cfg.max_replies_per_window} replies / {cfg.window_sec}s"
             f"{'  (defaults — tune from observed trips)' if is_default else ''}")
        _log("  signing    : ENFORCED (not configurable for the agent runner)")

    try:
        client = mq.open_subscriber(broker, f"agent/{cfg.agent_id}/inbox", on_message,
                                    client_id=f"synnoesis-agent-{cfg.agent_id}",
                                    on_ready=on_ready)
    except mq.SynBrokerError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    try:
        client.loop_forever()
    except KeyboardInterrupt:
        print("\nstopping.")
    finally:
        try:
            client.disconnect()
        except Exception:  # noqa: BLE001
            pass
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        prog="agent",
        description="run a model-backed agent on the mesh (verify -> model turn -> "
                    "signed reply). No tools: text in, text out.")
    ap.add_argument("--config", required=True, help="path to the agent JSON config")
    ap.add_argument("--max-age-sec", type=int, default=None,
                    help="freshness window; defaults to SYN_MAX_AGE_SEC")
    args = ap.parse_args(argv)

    try:
        cfg = load_config(args.config)
    except ConfigError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    max_age = args.max_age_sec
    if max_age is None:
        try:
            max_age = int(os.environ.get("SYN_MAX_AGE_SEC") or 300)
        except ValueError:
            print("error: SYN_MAX_AGE_SEC is not an integer", file=sys.stderr)
            return 2
    return run(cfg, max_age_sec=max_age)


if __name__ == "__main__":
    sys.exit(main())
